### ISSUE TITLE
render.py still has Django dependencies

### ISSUE THREAD

**Issue by geeknam** [mic159/react-render#1]
```python
from django.contrib.staticfiles import finders
from django.core.serializers.json import DjangoJSONEncoder
from django.utils.safestring import mark_safe
from django.conf import settings
```

**Comment by mic159** [comment]
Thanks Nam!

Fixed in 291a692.

I moved all the Django specific things into `react_render.django` and put the core into `react_render.core`.
I left `react_render.render` in there with a deprecation warning to make it backwards compatible.

Would you be able to take a look? If its all good, I'll release it to pypi.
